import type {Metadata} from "next";
import "./globals.css";
import localFont from "next/font/local";
import SmoothScroller from "@/components/ui/smoother/smoother";



const sofiaPro = localFont({
    src: [
        {
            path: './fonts/Sofia Pro UltraLight Az.woff',
            weight: '100',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro ExtraLight Az.woff',
            weight: '200',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro Light Az.woff',
            weight: '300',
            style: 'normal'

        },
        {
            path: './fonts/Sofia_Pro_Regular_Az.woff',
            weight: '400',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro Medium Az.woff',
            weight: '500',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro Semi Bold Az.woff',
            weight: '600',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro Bold Az.woff',
            weight: '700',
            style: 'normal'

        },
        {
            path: './fonts/Sofia Pro Black Az.woff',
            weight: '900',
            style: 'normal'

        }
    ]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children, header}: Readonly<{
    children: React.ReactNode;
    header: React.ReactNode;
}>) {
    return (
        <html lang="en">

        <body
            className={`${sofiaPro.className} antialiased overflow-x-hidden`}
        >
        {header}
        <main>
            <SmoothScroller>
                {children}
            </SmoothScroller>

        </main>

        </body>
        </html>
    );
}
